---
- name: MySQL Users
  hosts: webservers

  tasks:
    - name: add a mysql user for the server
      mysql_user: name={{ db_username }} host={{ inventory_hostname }}
                  password={{ db_password }} priv='ansible.*:ALL'
                  state=present
      delegate_to: databases[0]
